image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    before: |
      gp open README.md
      curl -L https://github.com/thatdot/quine/releases/download/v1.3.2/quine-1.3.2.jar -o quine-1.3.2.jar
      curl -L https://that.re/attempts -o attempts.json
ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
